/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreatePortfolioDto,
  UpdatePortfolioDto
} from '../myApi.schemas';




  /**
 * @summary Criar novo portfólio
 */
export const portfolioControllerCreate = <TData = AxiosResponse<void>>(
    createPortfolioDto: CreatePortfolioDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/portfolio`,
      createPortfolioDto,options
    );
  }
/**
 * @summary Listar todos os portfólios
 */
export const portfolioControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/portfolio`,options
    );
  }
/**
 * @summary Buscar portfólio por ID
 */
export const portfolioControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/portfolio/${id}`,options
    );
  }
/**
 * @summary Atualizar portfólio
 */
export const portfolioControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updatePortfolioDto: UpdatePortfolioDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/portfolio/${id}`,
      updatePortfolioDto,options
    );
  }
/**
 * @summary Remover portfólio
 */
export const portfolioControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/portfolio/${id}`,options
    );
  }
export type PortfolioControllerCreateResult = AxiosResponse<void>
export type PortfolioControllerFindAllResult = AxiosResponse<void>
export type PortfolioControllerFindOneResult = AxiosResponse<void>
export type PortfolioControllerUpdateResult = AxiosResponse<void>
export type PortfolioControllerRemoveResult = AxiosResponse<void>
