/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import type {
  CreateIntegrationDto,
  UpdateIntegrationDto
} from '../coopApi.schemas';

import { customFetcher } from '../../fetcher';

/**
 * @summary Criar nova integração
 */
export type integrationsControllerCreateResponse201 = {
  data: void
  status: 201
}

export type integrationsControllerCreateResponse401 = {
  data: void
  status: 401
}
    
export type integrationsControllerCreateResponseSuccess = (integrationsControllerCreateResponse201) & {
  headers: Headers;
};
export type integrationsControllerCreateResponseError = (integrationsControllerCreateResponse401) & {
  headers: Headers;
};

export type integrationsControllerCreateResponse = (integrationsControllerCreateResponseSuccess | integrationsControllerCreateResponseError)

export const getIntegrationsControllerCreateUrl = () => {


  

  return `/integrations`
}

export const integrationsControllerCreate = async (createIntegrationDto: CreateIntegrationDto, options?: RequestInit): Promise<integrationsControllerCreateResponse> => {
  
  return customFetcher<integrationsControllerCreateResponse>(getIntegrationsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createIntegrationDto,)
  }
);}


/**
 * @summary Listar todas as integrações
 */
export type integrationsControllerFindAllResponse200 = {
  data: void
  status: 200
}

export type integrationsControllerFindAllResponse401 = {
  data: void
  status: 401
}
    
export type integrationsControllerFindAllResponseSuccess = (integrationsControllerFindAllResponse200) & {
  headers: Headers;
};
export type integrationsControllerFindAllResponseError = (integrationsControllerFindAllResponse401) & {
  headers: Headers;
};

export type integrationsControllerFindAllResponse = (integrationsControllerFindAllResponseSuccess | integrationsControllerFindAllResponseError)

export const getIntegrationsControllerFindAllUrl = () => {


  

  return `/integrations`
}

export const integrationsControllerFindAll = async ( options?: RequestInit): Promise<integrationsControllerFindAllResponse> => {
  
  return customFetcher<integrationsControllerFindAllResponse>(getIntegrationsControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Buscar integração por ID
 */
export type integrationsControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type integrationsControllerFindOneResponse401 = {
  data: void
  status: 401
}

export type integrationsControllerFindOneResponse404 = {
  data: void
  status: 404
}
    
export type integrationsControllerFindOneResponseSuccess = (integrationsControllerFindOneResponse200) & {
  headers: Headers;
};
export type integrationsControllerFindOneResponseError = (integrationsControllerFindOneResponse401 | integrationsControllerFindOneResponse404) & {
  headers: Headers;
};

export type integrationsControllerFindOneResponse = (integrationsControllerFindOneResponseSuccess | integrationsControllerFindOneResponseError)

export const getIntegrationsControllerFindOneUrl = (id: string,) => {


  

  return `/integrations/${id}`
}

export const integrationsControllerFindOne = async (id: string, options?: RequestInit): Promise<integrationsControllerFindOneResponse> => {
  
  return customFetcher<integrationsControllerFindOneResponse>(getIntegrationsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Atualizar integração
 */
export type integrationsControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type integrationsControllerUpdateResponse401 = {
  data: void
  status: 401
}

export type integrationsControllerUpdateResponse404 = {
  data: void
  status: 404
}
    
export type integrationsControllerUpdateResponseSuccess = (integrationsControllerUpdateResponse200) & {
  headers: Headers;
};
export type integrationsControllerUpdateResponseError = (integrationsControllerUpdateResponse401 | integrationsControllerUpdateResponse404) & {
  headers: Headers;
};

export type integrationsControllerUpdateResponse = (integrationsControllerUpdateResponseSuccess | integrationsControllerUpdateResponseError)

export const getIntegrationsControllerUpdateUrl = (id: string,) => {


  

  return `/integrations/${id}`
}

export const integrationsControllerUpdate = async (id: string,
    updateIntegrationDto: UpdateIntegrationDto, options?: RequestInit): Promise<integrationsControllerUpdateResponse> => {
  
  return customFetcher<integrationsControllerUpdateResponse>(getIntegrationsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateIntegrationDto,)
  }
);}


/**
 * @summary Remover integração
 */
export type integrationsControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type integrationsControllerRemoveResponse401 = {
  data: void
  status: 401
}

export type integrationsControllerRemoveResponse404 = {
  data: void
  status: 404
}
    
export type integrationsControllerRemoveResponseSuccess = (integrationsControllerRemoveResponse200) & {
  headers: Headers;
};
export type integrationsControllerRemoveResponseError = (integrationsControllerRemoveResponse401 | integrationsControllerRemoveResponse404) & {
  headers: Headers;
};

export type integrationsControllerRemoveResponse = (integrationsControllerRemoveResponseSuccess | integrationsControllerRemoveResponseError)

export const getIntegrationsControllerRemoveUrl = (id: string,) => {


  

  return `/integrations/${id}`
}

export const integrationsControllerRemove = async (id: string, options?: RequestInit): Promise<integrationsControllerRemoveResponse> => {
  
  return customFetcher<integrationsControllerRemoveResponse>(getIntegrationsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


