/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateIntegrationDto,
  UpdateIntegrationDto
} from '.././model';





/**
 * @summary Criar nova integração
 */
export const integrationsControllerCreate = (
    createIntegrationDto: CreateIntegrationDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/integrations`,
      createIntegrationDto,options
    );
  }



export const getIntegrationsControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerCreate>>, TError,{data: CreateIntegrationDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerCreate>>, TError,{data: CreateIntegrationDto}, TContext> => {

const mutationKey = ['integrationsControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof integrationsControllerCreate>>, {data: CreateIntegrationDto}> = (props) => {
          const {data} = props ?? {};

          return  integrationsControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type IntegrationsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof integrationsControllerCreate>>>
    export type IntegrationsControllerCreateMutationBody = CreateIntegrationDto
    export type IntegrationsControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Criar nova integração
 */
export const useIntegrationsControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerCreate>>, TError,{data: CreateIntegrationDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof integrationsControllerCreate>>,
        TError,
        {data: CreateIntegrationDto},
        TContext
      > => {

      const mutationOptions = getIntegrationsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Listar todas as integrações
 */
export const integrationsControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/integrations`,options
    );
  }




export const getIntegrationsControllerFindAllQueryKey = () => {
    return [
    `/integrations`
    ] as const;
    }

    
export const getIntegrationsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof integrationsControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof integrationsControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIntegrationsControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof integrationsControllerFindAll>>> = ({ signal }) => integrationsControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof integrationsControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type IntegrationsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof integrationsControllerFindAll>>>
export type IntegrationsControllerFindAllQueryError = AxiosError<void>


/**
 * @summary Listar todas as integrações
 */

export function useIntegrationsControllerFindAll<TData = Awaited<ReturnType<typeof integrationsControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof integrationsControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getIntegrationsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Buscar integração por ID
 */
export const integrationsControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/integrations/${id}`,options
    );
  }




export const getIntegrationsControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/integrations/${id}`
    ] as const;
    }

    
export const getIntegrationsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof integrationsControllerFindOne>>, TError = AxiosError<void | void>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof integrationsControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIntegrationsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof integrationsControllerFindOne>>> = ({ signal }) => integrationsControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof integrationsControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type IntegrationsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof integrationsControllerFindOne>>>
export type IntegrationsControllerFindOneQueryError = AxiosError<void | void>


/**
 * @summary Buscar integração por ID
 */

export function useIntegrationsControllerFindOne<TData = Awaited<ReturnType<typeof integrationsControllerFindOne>>, TError = AxiosError<void | void>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof integrationsControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getIntegrationsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Atualizar integração
 */
export const integrationsControllerUpdate = (
    id: string,
    updateIntegrationDto: UpdateIntegrationDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/integrations/${id}`,
      updateIntegrationDto,options
    );
  }



export const getIntegrationsControllerUpdateMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerUpdate>>, TError,{id: string;data: UpdateIntegrationDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerUpdate>>, TError,{id: string;data: UpdateIntegrationDto}, TContext> => {

const mutationKey = ['integrationsControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof integrationsControllerUpdate>>, {id: string;data: UpdateIntegrationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  integrationsControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type IntegrationsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof integrationsControllerUpdate>>>
    export type IntegrationsControllerUpdateMutationBody = UpdateIntegrationDto
    export type IntegrationsControllerUpdateMutationError = AxiosError<void | void>

    /**
 * @summary Atualizar integração
 */
export const useIntegrationsControllerUpdate = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerUpdate>>, TError,{id: string;data: UpdateIntegrationDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof integrationsControllerUpdate>>,
        TError,
        {id: string;data: UpdateIntegrationDto},
        TContext
      > => {

      const mutationOptions = getIntegrationsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Remover integração
 */
export const integrationsControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/integrations/${id}`,options
    );
  }



export const getIntegrationsControllerRemoveMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['integrationsControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof integrationsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  integrationsControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type IntegrationsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof integrationsControllerRemove>>>
    
    export type IntegrationsControllerRemoveMutationError = AxiosError<void | void>

    /**
 * @summary Remover integração
 */
export const useIntegrationsControllerRemove = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof integrationsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getIntegrationsControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions);
    }
    