/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthControllerGetResetPasswordPageParams,
  LoginDto,
  RegisterDto,
  RequestMagicLinkDto,
  ResetPasswordDto
} from '../myApi.schemas';




  /**
 * @summary Registrar novo usuário
 */
export const authControllerRegister = <TData = AxiosResponse<void>>(
    registerDto: RegisterDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/register`,
      registerDto,options
    );
  }
/**
 * @summary Fazer login
 */
export const authControllerLogin = <TData = AxiosResponse<void>>(
    loginDto: LoginDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/login`,
      loginDto,options
    );
  }
/**
 * @summary Obter perfil do usuário autenticado
 */
export const authControllerGetProfile = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/auth/profile`,options
    );
  }
/**
 * @summary Solicitar Magic Link para recuperação de senha
 */
export const authControllerRequestMagicLink = <TData = AxiosResponse<void>>(
    requestMagicLinkDto: RequestMagicLinkDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/request-magic-link`,
      requestMagicLinkDto,options
    );
  }
/**
 * @summary Página de redefinição de senha (GET)
 */
export const authControllerGetResetPasswordPage = <TData = AxiosResponse<void>>(
    params: AuthControllerGetResetPasswordPageParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/auth/reset-password`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Redefinir senha usando Magic Link (POST)
 */
export const authControllerResetPassword = <TData = AxiosResponse<void>>(
    resetPasswordDto: ResetPasswordDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/reset-password`,
      resetPasswordDto,options
    );
  }
export type AuthControllerRegisterResult = AxiosResponse<void>
export type AuthControllerLoginResult = AxiosResponse<void>
export type AuthControllerGetProfileResult = AxiosResponse<void>
export type AuthControllerRequestMagicLinkResult = AxiosResponse<void>
export type AuthControllerGetResetPasswordPageResult = AxiosResponse<void>
export type AuthControllerResetPasswordResult = AxiosResponse<void>

export function default() {
    throw new Error('Function not implemented.');
}
export function default() {
    throw new Error('Function not implemented.');
}

