/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreatePortfolioDto,
  UpdatePortfolioDto
} from '.././model';





/**
 * @summary Criar novo portfólio
 */
export const portfolioControllerCreate = (
    createPortfolioDto: CreatePortfolioDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/portfolio`,
      createPortfolioDto,options
    );
  }



export const getPortfolioControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerCreate>>, TError,{data: CreatePortfolioDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerCreate>>, TError,{data: CreatePortfolioDto}, TContext> => {

const mutationKey = ['portfolioControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioControllerCreate>>, {data: CreatePortfolioDto}> = (props) => {
          const {data} = props ?? {};

          return  portfolioControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerCreate>>>
    export type PortfolioControllerCreateMutationBody = CreatePortfolioDto
    export type PortfolioControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Criar novo portfólio
 */
export const usePortfolioControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerCreate>>, TError,{data: CreatePortfolioDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof portfolioControllerCreate>>,
        TError,
        {data: CreatePortfolioDto},
        TContext
      > => {

      const mutationOptions = getPortfolioControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Listar todos os portfólios
 */
export const portfolioControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/portfolio`,options
    );
  }




export const getPortfolioControllerFindAllQueryKey = () => {
    return [
    `/portfolio`
    ] as const;
    }

    
export const getPortfolioControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof portfolioControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPortfolioControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof portfolioControllerFindAll>>> = ({ signal }) => portfolioControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type PortfolioControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerFindAll>>>
export type PortfolioControllerFindAllQueryError = AxiosError<void>


/**
 * @summary Listar todos os portfólios
 */

export function usePortfolioControllerFindAll<TData = Awaited<ReturnType<typeof portfolioControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPortfolioControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Buscar portfólio por ID
 */
export const portfolioControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/portfolio/${id}`,options
    );
  }




export const getPortfolioControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/portfolio/${id}`
    ] as const;
    }

    
export const getPortfolioControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof portfolioControllerFindOne>>, TError = AxiosError<void | void>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPortfolioControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof portfolioControllerFindOne>>> = ({ signal }) => portfolioControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type PortfolioControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerFindOne>>>
export type PortfolioControllerFindOneQueryError = AxiosError<void | void>


/**
 * @summary Buscar portfólio por ID
 */

export function usePortfolioControllerFindOne<TData = Awaited<ReturnType<typeof portfolioControllerFindOne>>, TError = AxiosError<void | void>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof portfolioControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPortfolioControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Atualizar portfólio
 */
export const portfolioControllerUpdate = (
    id: string,
    updatePortfolioDto: UpdatePortfolioDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/portfolio/${id}`,
      updatePortfolioDto,options
    );
  }



export const getPortfolioControllerUpdateMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerUpdate>>, TError,{id: string;data: UpdatePortfolioDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerUpdate>>, TError,{id: string;data: UpdatePortfolioDto}, TContext> => {

const mutationKey = ['portfolioControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioControllerUpdate>>, {id: string;data: UpdatePortfolioDto}> = (props) => {
          const {id,data} = props ?? {};

          return  portfolioControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerUpdate>>>
    export type PortfolioControllerUpdateMutationBody = UpdatePortfolioDto
    export type PortfolioControllerUpdateMutationError = AxiosError<void | void>

    /**
 * @summary Atualizar portfólio
 */
export const usePortfolioControllerUpdate = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerUpdate>>, TError,{id: string;data: UpdatePortfolioDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof portfolioControllerUpdate>>,
        TError,
        {id: string;data: UpdatePortfolioDto},
        TContext
      > => {

      const mutationOptions = getPortfolioControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Remover portfólio
 */
export const portfolioControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/portfolio/${id}`,options
    );
  }



export const getPortfolioControllerRemoveMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['portfolioControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof portfolioControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  portfolioControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PortfolioControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof portfolioControllerRemove>>>
    
    export type PortfolioControllerRemoveMutationError = AxiosError<void | void>

    /**
 * @summary Remover portfólio
 */
export const usePortfolioControllerRemove = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof portfolioControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof portfolioControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPortfolioControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions);
    }
    