/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordDto {
  /** Token do magic link recebido por email */
  token: string;
  /**
   * Nova senha (mínimo 6 caracteres)
   * @minLength 6
   */
  newPassword: string;
}
