/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateSocialDto,
  UpdateSocialDto
} from '.././model';





/**
 * @summary Criar interação social
 */
export const socialControllerCreate = (
    createSocialDto: CreateSocialDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/social`,
      createSocialDto,options
    );
  }



export const getSocialControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialControllerCreate>>, TError,{data: CreateSocialDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof socialControllerCreate>>, TError,{data: CreateSocialDto}, TContext> => {

const mutationKey = ['socialControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof socialControllerCreate>>, {data: CreateSocialDto}> = (props) => {
          const {data} = props ?? {};

          return  socialControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SocialControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof socialControllerCreate>>>
    export type SocialControllerCreateMutationBody = CreateSocialDto
    export type SocialControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Criar interação social
 */
export const useSocialControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialControllerCreate>>, TError,{data: CreateSocialDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof socialControllerCreate>>,
        TError,
        {data: CreateSocialDto},
        TContext
      > => {

      const mutationOptions = getSocialControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Listar todas as interações
 */
export const socialControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/social`,options
    );
  }




export const getSocialControllerFindAllQueryKey = () => {
    return [
    `/social`
    ] as const;
    }

    
export const getSocialControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof socialControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof socialControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSocialControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof socialControllerFindAll>>> = ({ signal }) => socialControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof socialControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type SocialControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof socialControllerFindAll>>>
export type SocialControllerFindAllQueryError = AxiosError<void>


/**
 * @summary Listar todas as interações
 */

export function useSocialControllerFindAll<TData = Awaited<ReturnType<typeof socialControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof socialControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSocialControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Buscar interação por ID
 */
export const socialControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/social/${id}`,options
    );
  }




export const getSocialControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/social/${id}`
    ] as const;
    }

    
export const getSocialControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof socialControllerFindOne>>, TError = AxiosError<void | void>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof socialControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSocialControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof socialControllerFindOne>>> = ({ signal }) => socialControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof socialControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type SocialControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof socialControllerFindOne>>>
export type SocialControllerFindOneQueryError = AxiosError<void | void>


/**
 * @summary Buscar interação por ID
 */

export function useSocialControllerFindOne<TData = Awaited<ReturnType<typeof socialControllerFindOne>>, TError = AxiosError<void | void>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof socialControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSocialControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Atualizar interação
 */
export const socialControllerUpdate = (
    id: string,
    updateSocialDto: UpdateSocialDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/social/${id}`,
      updateSocialDto,options
    );
  }



export const getSocialControllerUpdateMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialControllerUpdate>>, TError,{id: string;data: UpdateSocialDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof socialControllerUpdate>>, TError,{id: string;data: UpdateSocialDto}, TContext> => {

const mutationKey = ['socialControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof socialControllerUpdate>>, {id: string;data: UpdateSocialDto}> = (props) => {
          const {id,data} = props ?? {};

          return  socialControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SocialControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof socialControllerUpdate>>>
    export type SocialControllerUpdateMutationBody = UpdateSocialDto
    export type SocialControllerUpdateMutationError = AxiosError<void | void>

    /**
 * @summary Atualizar interação
 */
export const useSocialControllerUpdate = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialControllerUpdate>>, TError,{id: string;data: UpdateSocialDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof socialControllerUpdate>>,
        TError,
        {id: string;data: UpdateSocialDto},
        TContext
      > => {

      const mutationOptions = getSocialControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Remover interação
 */
export const socialControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/social/${id}`,options
    );
  }



export const getSocialControllerRemoveMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof socialControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['socialControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof socialControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  socialControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SocialControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof socialControllerRemove>>>
    
    export type SocialControllerRemoveMutationError = AxiosError<void | void>

    /**
 * @summary Remover interação
 */
export const useSocialControllerRemove = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof socialControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof socialControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getSocialControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions);
    }
    