/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateSocialDto,
  UpdateSocialDto
} from '../coopApi.schemas';




  export const getSocial = () => {
/**
 * @summary Criar interação social
 */
const socialControllerCreate = <TData = AxiosResponse<void>>(
    createSocialDto: CreateSocialDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/social`,
      createSocialDto,options
    );
  }
/**
 * @summary Listar todas as interações
 */
const socialControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/social`,options
    );
  }
/**
 * @summary Buscar interação por ID
 */
const socialControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/social/${id}`,options
    );
  }
/**
 * @summary Atualizar interação
 */
const socialControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateSocialDto: UpdateSocialDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/social/${id}`,
      updateSocialDto,options
    );
  }
/**
 * @summary Remover interação
 */
const socialControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/social/${id}`,options
    );
  }
return {socialControllerCreate,socialControllerFindAll,socialControllerFindOne,socialControllerUpdate,socialControllerRemove}};
export type SocialControllerCreateResult = AxiosResponse<void>
export type SocialControllerFindAllResult = AxiosResponse<void>
export type SocialControllerFindOneResult = AxiosResponse<void>
export type SocialControllerUpdateResult = AxiosResponse<void>
export type SocialControllerRemoveResult = AxiosResponse<void>
