/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import type {
  CreatePortfolioDto,
  UpdatePortfolioDto
} from '../coopApi.schemas';

import { customFetcher } from '../../fetcher';

/**
 * @summary Cria um novo portfólio
 */
export type portfoliosControllerCreateResponse201 = {
  data: any
  status: 201
}
    
export type portfoliosControllerCreateResponseSuccess = (portfoliosControllerCreateResponse201) & {
  headers: Headers;
};

export type portfoliosControllerCreateResponse = (portfoliosControllerCreateResponseSuccess)

export const getPortfoliosControllerCreateUrl = () => `/portfolios`

export const portfoliosControllerCreate = async (createPortfolioDto: CreatePortfolioDto, options?: RequestInit): Promise<portfoliosControllerCreateResponse> => {
  return customFetcher<portfoliosControllerCreateResponse>(getPortfoliosControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPortfolioDto)
  });
}


/**
 * @summary Lista todos os portfólios
 */
export type portfoliosControllerFindAllResponse200 = {
  data: any
  status: 200
}
    
export type portfoliosControllerFindAllResponseSuccess = (portfoliosControllerFindAllResponse200) & {
  headers: Headers;
};

export type portfoliosControllerFindAllResponse = (portfoliosControllerFindAllResponseSuccess)

export const getPortfoliosControllerFindAllUrl = () => `/portfolios`

export const portfoliosControllerFindAll = async ( options?: RequestInit): Promise<portfoliosControllerFindAllResponse> => {
  return customFetcher<portfoliosControllerFindAllResponse>(getPortfoliosControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
  });
}


/**
 * @summary Busca um portfólio pelo ID
 */
export type portfoliosControllerFindOneResponse200 = {
  data: any
  status: 200
}
    
export type portfoliosControllerFindOneResponseSuccess = (portfoliosControllerFindOneResponse200) & {
  headers: Headers;
};

export type portfoliosControllerFindOneResponse = (portfoliosControllerFindOneResponseSuccess)

export const getPortfoliosControllerFindOneUrl = (id: number) => `/portfolios/${id}`

export const portfoliosControllerFindOne = async (id: number, options?: RequestInit): Promise<portfoliosControllerFindOneResponse> => {
  return customFetcher<portfoliosControllerFindOneResponse>(getPortfoliosControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
  });
}


/**
 * @summary Atualiza um portfólio
 */
export type portfoliosControllerUpdateResponse200 = {
  data: any
  status: 200
}
    
export type portfoliosControllerUpdateResponseSuccess = (portfoliosControllerUpdateResponse200) & {
  headers: Headers;
};

export type portfoliosControllerUpdateResponse = (portfoliosControllerUpdateResponseSuccess)

export const getPortfoliosControllerUpdateUrl = (id: number) => `/portfolios/${id}`

export const portfoliosControllerUpdate = async (id: number, updatePortfolioDto: UpdatePortfolioDto, options?: RequestInit): Promise<portfoliosControllerUpdateResponse> => {
  return customFetcher<portfoliosControllerUpdateResponse>(getPortfoliosControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePortfolioDto)
  });
}


/**
 * @summary Remove um portfólio
 */
export type portfoliosControllerRemoveResponse200 = {
  data: any
  status: 200
}
    
export type portfoliosControllerRemoveResponseSuccess = (portfoliosControllerRemoveResponse200) & {
  headers: Headers;
};

export type portfoliosControllerRemoveResponse = (portfoliosControllerRemoveResponseSuccess)

export const getPortfoliosControllerRemoveUrl = (id: number) => `/portfolios/${id}`

export const portfoliosControllerRemove = async (id: number, options?: RequestInit): Promise<portfoliosControllerRemoveResponse> => {
  return customFetcher<portfoliosControllerRemoveResponse>(getPortfoliosControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
  });
}


/**
 * @summary Obtém o portfólio do usuário autenticado
 */
export type portfoliosControllerGetMyProfileResponse200 = {
  data: any
  status: 200
}
    
export type portfoliosControllerGetMyProfileResponseSuccess = (portfoliosControllerGetMyProfileResponse200) & {
  headers: Headers;
};

export type portfoliosControllerGetMyProfileResponse = (portfoliosControllerGetMyProfileResponseSuccess)

export const getPortfoliosControllerGetMyProfileUrl = () => `/portfolios/me/profile`

export const portfoliosControllerGetMyProfile = async ( options?: RequestInit): Promise<portfoliosControllerGetMyProfileResponse> => {
  return customFetcher<portfoliosControllerGetMyProfileResponse>(getPortfoliosControllerGetMyProfileUrl(),
  {      
    ...options,
    method: 'GET'
  });
}
