/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
export interface UpdateUserDto { [key: string]: unknown }

export interface CreatePortfolioDto { [key: string]: unknown }

export interface UpdatePortfolioDto { [key: string]: unknown }

export interface RegisterDto {
  /**
   * Nome de usuário único
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** Email do usuário */
  email: string;
  /**
   * Senha do usuário
   * @minLength 6
   */
  password: string;
}

export interface LoginDto {
  /** Username ou email */
  usernameOrEmail: string;
  /** Senha do usuário */
  password: string;
}

export interface RequestMagicLinkDto {
  /** Email do usuário para receber o magic link */
  email: string;
}

export interface ResetPasswordDto {
  /** Token do magic link recebido por email */
  token: string;
  /**
   * Nova senha (mínimo 6 caracteres)
   * @minLength 6
   */
  newPassword: string;
}

export interface CreateProjectDto { [key: string]: unknown }

export interface UpdateProjectDto { [key: string]: unknown }

export interface CreateSocialDto { [key: string]: unknown }

export interface UpdateSocialDto { [key: string]: unknown }

export interface CreateIntegrationDto { [key: string]: unknown }

export interface UpdateIntegrationDto { [key: string]: unknown }

export interface CreateNotificationDto { [key: string]: unknown }

export interface UpdateNotificationDto { [key: string]: unknown }

export type AuthControllerGetResetPasswordPageParams = {
token: string;
};

