/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateNotificationDto,
  UpdateNotificationDto
} from '../myApi.schemas';




  /**
 * @summary Criar nova notificação
 */
export const notificationsControllerCreate = <TData = AxiosResponse<void>>(
    createNotificationDto: CreateNotificationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/notifications`,
      createNotificationDto,options
    );
  }
/**
 * @summary Listar todas as notificações
 */
export const notificationsControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/notifications`,options
    );
  }
/**
 * @summary Buscar notificação por ID
 */
export const notificationsControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/notifications/${id}`,options
    );
  }
/**
 * @summary Atualizar notificação
 */
export const notificationsControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateNotificationDto: UpdateNotificationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/notifications/${id}`,
      updateNotificationDto,options
    );
  }
/**
 * @summary Remover notificação
 */
export const notificationsControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/notifications/${id}`,options
    );
  }
export type NotificationsControllerCreateResult = AxiosResponse<void>
export type NotificationsControllerFindAllResult = AxiosResponse<void>
export type NotificationsControllerFindOneResult = AxiosResponse<void>
export type NotificationsControllerUpdateResult = AxiosResponse<void>
export type NotificationsControllerRemoveResult = AxiosResponse<void>
