/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateIntegrationDto,
  UpdateIntegrationDto
} from '../myApi.schemas';




  /**
 * @summary Criar nova integração
 */
export const integrationsControllerCreate = <TData = AxiosResponse<void>>(
    createIntegrationDto: CreateIntegrationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/integrations`,
      createIntegrationDto,options
    );
  }
/**
 * @summary Listar todas as integrações
 */
export const integrationsControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/integrations`,options
    );
  }
/**
 * @summary Buscar integração por ID
 */
export const integrationsControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/integrations/${id}`,options
    );
  }
/**
 * @summary Atualizar integração
 */
export const integrationsControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateIntegrationDto: UpdateIntegrationDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/integrations/${id}`,
      updateIntegrationDto,options
    );
  }
/**
 * @summary Remover integração
 */
export const integrationsControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/integrations/${id}`,options
    );
  }
export type IntegrationsControllerCreateResult = AxiosResponse<void>
export type IntegrationsControllerFindAllResult = AxiosResponse<void>
export type IntegrationsControllerFindOneResult = AxiosResponse<void>
export type IntegrationsControllerUpdateResult = AxiosResponse<void>
export type IntegrationsControllerRemoveResult = AxiosResponse<void>
