/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateProjectDto,
  UpdateProjectDto
} from '../myApi.schemas';




  /**
 * @summary Criar novo projeto
 */
export const projectsControllerCreate = <TData = AxiosResponse<void>>(
    createProjectDto: CreateProjectDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/projects`,
      createProjectDto,options
    );
  }
/**
 * @summary Listar todos os projetos
 */
export const projectsControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/projects`,options
    );
  }
/**
 * @summary Buscar projeto por ID
 */
export const projectsControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/projects/${id}`,options
    );
  }
/**
 * @summary Atualizar projeto
 */
export const projectsControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateProjectDto: UpdateProjectDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/projects/${id}`,
      updateProjectDto,options
    );
  }
/**
 * @summary Remover projeto
 */
export const projectsControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/projects/${id}`,options
    );
  }
export type ProjectsControllerCreateResult = AxiosResponse<void>
export type ProjectsControllerFindAllResult = AxiosResponse<void>
export type ProjectsControllerFindOneResult = AxiosResponse<void>
export type ProjectsControllerUpdateResult = AxiosResponse<void>
export type ProjectsControllerRemoveResult = AxiosResponse<void>
