/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import type {
  UpdateUserDto
} from '../coopApi.schemas';


/**
 * @summary Listar todos os usuários
 */
export type usersControllerFindAllResponse200 = {
  data: void
  status: 200
}

export type usersControllerFindAllResponse401 = {
  data: void
  status: 401
}
    
export type usersControllerFindAllResponseSuccess = (usersControllerFindAllResponse200) & {
  headers: Headers;
};
export type usersControllerFindAllResponseError = (usersControllerFindAllResponse401) & {
  headers: Headers;
};

export type usersControllerFindAllResponse = (usersControllerFindAllResponseSuccess | usersControllerFindAllResponseError)

export const getUsersControllerFindAllUrl = () => {


  

  return `/users`
}

export const usersControllerFindAll = async ( options?: RequestInit): Promise<usersControllerFindAllResponse> => {
  
  const res = await fetch(getUsersControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerFindAllResponse
}


/**
 * @summary Buscar usuário por ID
 */
export type usersControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type usersControllerFindOneResponse401 = {
  data: void
  status: 401
}

export type usersControllerFindOneResponse404 = {
  data: void
  status: 404
}
    
export type usersControllerFindOneResponseSuccess = (usersControllerFindOneResponse200) & {
  headers: Headers;
};
export type usersControllerFindOneResponseError = (usersControllerFindOneResponse401 | usersControllerFindOneResponse404) & {
  headers: Headers;
};

export type usersControllerFindOneResponse = (usersControllerFindOneResponseSuccess | usersControllerFindOneResponseError)

export const getUsersControllerFindOneUrl = (id: string,) => {


  

  return `/users/${id}`
}

export const usersControllerFindOne = async (id: string, options?: RequestInit): Promise<usersControllerFindOneResponse> => {
  
  const res = await fetch(getUsersControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerFindOneResponse
}


/**
 * @summary Atualizar dados do usuário
 */
export type usersControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type usersControllerUpdateResponse401 = {
  data: void
  status: 401
}

export type usersControllerUpdateResponse404 = {
  data: void
  status: 404
}
    
export type usersControllerUpdateResponseSuccess = (usersControllerUpdateResponse200) & {
  headers: Headers;
};
export type usersControllerUpdateResponseError = (usersControllerUpdateResponse401 | usersControllerUpdateResponse404) & {
  headers: Headers;
};

export type usersControllerUpdateResponse = (usersControllerUpdateResponseSuccess | usersControllerUpdateResponseError)

export const getUsersControllerUpdateUrl = (id: string,) => {


  

  return `/users/${id}`
}

export const usersControllerUpdate = async (id: string,
    updateUserDto: UpdateUserDto, options?: RequestInit): Promise<usersControllerUpdateResponse> => {
  
  const res = await fetch(getUsersControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerUpdateResponse
}


/**
 * @summary Remover usuário
 */
export type usersControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type usersControllerRemoveResponse401 = {
  data: void
  status: 401
}

export type usersControllerRemoveResponse404 = {
  data: void
  status: 404
}
    
export type usersControllerRemoveResponseSuccess = (usersControllerRemoveResponse200) & {
  headers: Headers;
};
export type usersControllerRemoveResponseError = (usersControllerRemoveResponse401 | usersControllerRemoveResponse404) & {
  headers: Headers;
};

export type usersControllerRemoveResponse = (usersControllerRemoveResponseSuccess | usersControllerRemoveResponseError)

export const getUsersControllerRemoveUrl = (id: string,) => {


  

  return `/users/${id}`
}

export const usersControllerRemove = async (id: string, options?: RequestInit): Promise<usersControllerRemoveResponse> => {
  
  const res = await fetch(getUsersControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerRemoveResponse
}


