/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  UpdateUserDto
} from '../coopApi.schemas';




  export const getUsers = () => {
/**
 * @summary Listar todos os usuários
 */
const usersControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users`,options
    );
  }
/**
 * @summary Buscar usuário por ID
 */
const usersControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users/${id}`,options
    );
  }
/**
 * @summary Atualizar dados do usuário
 */
const usersControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/users/${id}`,
      updateUserDto,options
    );
  }
/**
 * @summary Remover usuário
 */
const usersControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/users/${id}`,options
    );
  }
return {usersControllerFindAll,usersControllerFindOne,usersControllerUpdate,usersControllerRemove}};
export type UsersControllerFindAllResult = AxiosResponse<void>
export type UsersControllerFindOneResult = AxiosResponse<void>
export type UsersControllerUpdateResult = AxiosResponse<void>
export type UsersControllerRemoveResult = AxiosResponse<void>
