/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import type {
  CreateProjectDto,
  UpdateProjectDto
} from '../coopApi.schemas';


/**
 * @summary Criar novo projeto
 */
export type projectsControllerCreateResponse201 = {
  data: void
  status: 201
}

export type projectsControllerCreateResponse401 = {
  data: void
  status: 401
}
    
export type projectsControllerCreateResponseSuccess = (projectsControllerCreateResponse201) & {
  headers: Headers;
};
export type projectsControllerCreateResponseError = (projectsControllerCreateResponse401) & {
  headers: Headers;
};

export type projectsControllerCreateResponse = (projectsControllerCreateResponseSuccess | projectsControllerCreateResponseError)

export const getProjectsControllerCreateUrl = () => {


  

  return `/projects`
}

export const projectsControllerCreate = async (createProjectDto: CreateProjectDto, options?: RequestInit): Promise<projectsControllerCreateResponse> => {
  
  const res = await fetch(getProjectsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerCreateResponse
}


/**
 * @summary Listar todos os projetos
 */
export type projectsControllerFindAllResponse200 = {
  data: void
  status: 200
}

export type projectsControllerFindAllResponse401 = {
  data: void
  status: 401
}
    
export type projectsControllerFindAllResponseSuccess = (projectsControllerFindAllResponse200) & {
  headers: Headers;
};
export type projectsControllerFindAllResponseError = (projectsControllerFindAllResponse401) & {
  headers: Headers;
};

export type projectsControllerFindAllResponse = (projectsControllerFindAllResponseSuccess | projectsControllerFindAllResponseError)

export const getProjectsControllerFindAllUrl = () => {


  

  return `/projects`
}

export const projectsControllerFindAll = async ( options?: RequestInit): Promise<projectsControllerFindAllResponse> => {
  
  const res = await fetch(getProjectsControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerFindAllResponse
}


/**
 * @summary Buscar projeto por ID
 */
export type projectsControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type projectsControllerFindOneResponse401 = {
  data: void
  status: 401
}

export type projectsControllerFindOneResponse404 = {
  data: void
  status: 404
}
    
export type projectsControllerFindOneResponseSuccess = (projectsControllerFindOneResponse200) & {
  headers: Headers;
};
export type projectsControllerFindOneResponseError = (projectsControllerFindOneResponse401 | projectsControllerFindOneResponse404) & {
  headers: Headers;
};

export type projectsControllerFindOneResponse = (projectsControllerFindOneResponseSuccess | projectsControllerFindOneResponseError)

export const getProjectsControllerFindOneUrl = (id: string,) => {


  

  return `/projects/${id}`
}

export const projectsControllerFindOne = async (id: string, options?: RequestInit): Promise<projectsControllerFindOneResponse> => {
  
  const res = await fetch(getProjectsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerFindOneResponse
}


/**
 * @summary Atualizar projeto
 */
export type projectsControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type projectsControllerUpdateResponse401 = {
  data: void
  status: 401
}

export type projectsControllerUpdateResponse404 = {
  data: void
  status: 404
}
    
export type projectsControllerUpdateResponseSuccess = (projectsControllerUpdateResponse200) & {
  headers: Headers;
};
export type projectsControllerUpdateResponseError = (projectsControllerUpdateResponse401 | projectsControllerUpdateResponse404) & {
  headers: Headers;
};

export type projectsControllerUpdateResponse = (projectsControllerUpdateResponseSuccess | projectsControllerUpdateResponseError)

export const getProjectsControllerUpdateUrl = (id: string,) => {


  

  return `/projects/${id}`
}

export const projectsControllerUpdate = async (id: string,
    updateProjectDto: UpdateProjectDto, options?: RequestInit): Promise<projectsControllerUpdateResponse> => {
  
  const res = await fetch(getProjectsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProjectDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerUpdateResponse
}


/**
 * @summary Remover projeto
 */
export type projectsControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type projectsControllerRemoveResponse401 = {
  data: void
  status: 401
}

export type projectsControllerRemoveResponse404 = {
  data: void
  status: 404
}
    
export type projectsControllerRemoveResponseSuccess = (projectsControllerRemoveResponse200) & {
  headers: Headers;
};
export type projectsControllerRemoveResponseError = (projectsControllerRemoveResponse401 | projectsControllerRemoveResponse404) & {
  headers: Headers;
};

export type projectsControllerRemoveResponse = (projectsControllerRemoveResponseSuccess | projectsControllerRemoveResponseError)

export const getProjectsControllerRemoveUrl = (id: string,) => {


  

  return `/projects/${id}`
}

export const projectsControllerRemove = async (id: string, options?: RequestInit): Promise<projectsControllerRemoveResponse> => {
  
  const res = await fetch(getProjectsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerRemoveResponse
}


/**
 * @summary Entrar em um projeto (incrementa integrantes)
 */
export type projectsControllerJoinResponse200 = {
  data: void
  status: 200
}

export type projectsControllerJoinResponse400 = {
  data: void
  status: 400
}
    
export type projectsControllerJoinResponseSuccess = (projectsControllerJoinResponse200) & {
  headers: Headers;
};
export type projectsControllerJoinResponseError = (projectsControllerJoinResponse400) & {
  headers: Headers;
};

export type projectsControllerJoinResponse = (projectsControllerJoinResponseSuccess | projectsControllerJoinResponseError)

export const getProjectsControllerJoinUrl = (id: string,) => {


  

  return `/projects/${id}/join`
}

export const projectsControllerJoin = async (id: string, options?: RequestInit): Promise<projectsControllerJoinResponse> => {
  
  const res = await fetch(getProjectsControllerJoinUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerJoinResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerJoinResponse
}


/**
 * @summary Sair de um projeto (decrementa integrantes)
 */
export type projectsControllerLeaveResponse200 = {
  data: void
  status: 200
}

export type projectsControllerLeaveResponse400 = {
  data: void
  status: 400
}
    
export type projectsControllerLeaveResponseSuccess = (projectsControllerLeaveResponse200) & {
  headers: Headers;
};
export type projectsControllerLeaveResponseError = (projectsControllerLeaveResponse400) & {
  headers: Headers;
};

export type projectsControllerLeaveResponse = (projectsControllerLeaveResponseSuccess | projectsControllerLeaveResponseError)

export const getProjectsControllerLeaveUrl = (id: string,) => {


  

  return `/projects/${id}/leave`
}

export const projectsControllerLeave = async (id: string, options?: RequestInit): Promise<projectsControllerLeaveResponse> => {
  
  const res = await fetch(getProjectsControllerLeaveUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: projectsControllerLeaveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as projectsControllerLeaveResponse
}


