/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateProjectDto,
  UpdateProjectDto
} from '.././model';





/**
 * @summary Criar novo projeto
 */
export const projectsControllerCreate = (
    createProjectDto: CreateProjectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/projects`,
      createProjectDto,options
    );
  }



export const getProjectsControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError,{data: CreateProjectDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError,{data: CreateProjectDto}, TContext> => {

const mutationKey = ['projectsControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerCreate>>, {data: CreateProjectDto}> = (props) => {
          const {data} = props ?? {};

          return  projectsControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerCreate>>>
    export type ProjectsControllerCreateMutationBody = CreateProjectDto
    export type ProjectsControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Criar novo projeto
 */
export const useProjectsControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError,{data: CreateProjectDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerCreate>>,
        TError,
        {data: CreateProjectDto},
        TContext
      > => {

      const mutationOptions = getProjectsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Listar todos os projetos
 */
export const projectsControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/projects`,options
    );
  }




export const getProjectsControllerFindAllQueryKey = () => {
    return [
    `/projects`
    ] as const;
    }

    
export const getProjectsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerFindAll>>> = ({ signal }) => projectsControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type ProjectsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerFindAll>>>
export type ProjectsControllerFindAllQueryError = AxiosError<void>


/**
 * @summary Listar todos os projetos
 */

export function useProjectsControllerFindAll<TData = Awaited<ReturnType<typeof projectsControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getProjectsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Buscar projeto por ID
 */
export const projectsControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/projects/${id}`,options
    );
  }




export const getProjectsControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/projects/${id}`
    ] as const;
    }

    
export const getProjectsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerFindOne>>, TError = AxiosError<void | void>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerFindOne>>> = ({ signal }) => projectsControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type ProjectsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerFindOne>>>
export type ProjectsControllerFindOneQueryError = AxiosError<void | void>


/**
 * @summary Buscar projeto por ID
 */

export function useProjectsControllerFindOne<TData = Awaited<ReturnType<typeof projectsControllerFindOne>>, TError = AxiosError<void | void>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getProjectsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Atualizar projeto
 */
export const projectsControllerUpdate = (
    id: string,
    updateProjectDto: UpdateProjectDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/projects/${id}`,
      updateProjectDto,options
    );
  }



export const getProjectsControllerUpdateMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError,{id: string;data: UpdateProjectDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError,{id: string;data: UpdateProjectDto}, TContext> => {

const mutationKey = ['projectsControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerUpdate>>, {id: string;data: UpdateProjectDto}> = (props) => {
          const {id,data} = props ?? {};

          return  projectsControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerUpdate>>>
    export type ProjectsControllerUpdateMutationBody = UpdateProjectDto
    export type ProjectsControllerUpdateMutationError = AxiosError<void | void>

    /**
 * @summary Atualizar projeto
 */
export const useProjectsControllerUpdate = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError,{id: string;data: UpdateProjectDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerUpdate>>,
        TError,
        {id: string;data: UpdateProjectDto},
        TContext
      > => {

      const mutationOptions = getProjectsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Remover projeto
 */
export const projectsControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/projects/${id}`,options
    );
  }



export const getProjectsControllerRemoveMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['projectsControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  projectsControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerRemove>>>
    
    export type ProjectsControllerRemoveMutationError = AxiosError<void | void>

    /**
 * @summary Remover projeto
 */
export const useProjectsControllerRemove = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getProjectsControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions);
    }
    