/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import type {
  AuthControllerGetResetPasswordPageParams,
  LoginDto,
  RegisterDto,
  RequestMagicLinkDto,
  ResetPasswordDto
} from '../coopApi.schemas';

import { customFetcher } from '../../fetcher';

/**
 * @summary Registrar novo usuário
 */
export type authControllerRegisterResponse201 = {
  data: void
  status: 201
}

export type authControllerRegisterResponse409 = {
  data: void
  status: 409
}
    
export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse201) & {
  headers: Headers;
};
export type authControllerRegisterResponseError = (authControllerRegisterResponse409) & {
  headers: Headers;
};

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess | authControllerRegisterResponseError)

export const getAuthControllerRegisterUrl = () => {


  

  return `/auth/register`
}

export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<authControllerRegisterResponse> => {
  
  return customFetcher<authControllerRegisterResponse>(getAuthControllerRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerDto,)
  }
);}


/**
 * @summary Fazer login
 */
export type authControllerLoginResponse200 = {
  data: void
  status: 200
}

export type authControllerLoginResponse401 = {
  data: void
  status: 401
}
    
export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
export type authControllerLoginResponseError = (authControllerLoginResponse401) & {
  headers: Headers;
};

export type authControllerLoginResponse = (authControllerLoginResponseSuccess | authControllerLoginResponseError)

export const getAuthControllerLoginUrl = () => {


  

  return `/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<authControllerLoginResponse> => {
  
  return customFetcher<authControllerLoginResponse>(getAuthControllerLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
);}


/**
 * @summary Obter perfil do usuário autenticado
 */
export type authControllerGetProfileResponse200 = {
  data: void
  status: 200
}

export type authControllerGetProfileResponse401 = {
  data: void
  status: 401
}
    
export type authControllerGetProfileResponseSuccess = (authControllerGetProfileResponse200) & {
  headers: Headers;
};
export type authControllerGetProfileResponseError = (authControllerGetProfileResponse401) & {
  headers: Headers;
};

export type authControllerGetProfileResponse = (authControllerGetProfileResponseSuccess | authControllerGetProfileResponseError)

export const getAuthControllerGetProfileUrl = () => {


  

  return `/auth/profile`
}

export const authControllerGetProfile = async ( options?: RequestInit): Promise<authControllerGetProfileResponse> => {
  
  return customFetcher<authControllerGetProfileResponse>(getAuthControllerGetProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Solicitar Magic Link para recuperação de senha
 */
export type authControllerRequestMagicLinkResponse200 = {
  data: void
  status: 200
}
    
export type authControllerRequestMagicLinkResponseSuccess = (authControllerRequestMagicLinkResponse200) & {
  headers: Headers;
};
;

export type authControllerRequestMagicLinkResponse = (authControllerRequestMagicLinkResponseSuccess)

export const getAuthControllerRequestMagicLinkUrl = () => {


  

  return `/auth/request-magic-link`
}

export const authControllerRequestMagicLink = async (requestMagicLinkDto: RequestMagicLinkDto, options?: RequestInit): Promise<authControllerRequestMagicLinkResponse> => {
  
  return customFetcher<authControllerRequestMagicLinkResponse>(getAuthControllerRequestMagicLinkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestMagicLinkDto,)
  }
);}


/**
 * @summary Página de redefinição de senha (GET)
 */
export type authControllerGetResetPasswordPageResponse200 = {
  data: void
  status: 200
}
    
export type authControllerGetResetPasswordPageResponseSuccess = (authControllerGetResetPasswordPageResponse200) & {
  headers: Headers;
};
;

export type authControllerGetResetPasswordPageResponse = (authControllerGetResetPasswordPageResponseSuccess)

export const getAuthControllerGetResetPasswordPageUrl = (params: AuthControllerGetResetPasswordPageParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/reset-password?${stringifiedParams}` : `/auth/reset-password`
}

export const authControllerGetResetPasswordPage = async (params: AuthControllerGetResetPasswordPageParams, options?: RequestInit): Promise<authControllerGetResetPasswordPageResponse> => {
  
  return customFetcher<authControllerGetResetPasswordPageResponse>(getAuthControllerGetResetPasswordPageUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Redefinir senha usando Magic Link (POST)
 */
export type authControllerResetPasswordResponse200 = {
  data: void
  status: 200
}

export type authControllerResetPasswordResponse400 = {
  data: void
  status: 400
}

export type authControllerResetPasswordResponse404 = {
  data: void
  status: 404
}
    
export type authControllerResetPasswordResponseSuccess = (authControllerResetPasswordResponse200) & {
  headers: Headers;
};
export type authControllerResetPasswordResponseError = (authControllerResetPasswordResponse400 | authControllerResetPasswordResponse404) & {
  headers: Headers;
};

export type authControllerResetPasswordResponse = (authControllerResetPasswordResponseSuccess | authControllerResetPasswordResponseError)

export const getAuthControllerResetPasswordUrl = () => {


  

  return `/auth/reset-password`
}

export const authControllerResetPassword = async (resetPasswordDto: ResetPasswordDto, options?: RequestInit): Promise<authControllerResetPasswordResponse> => {
  
  return customFetcher<authControllerResetPasswordResponse>(getAuthControllerResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordDto,)
  }
);}


