/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
export interface UpdateUserDto { [key: string]: unknown }

export interface CreatePortfolioDto { [key: string]: unknown }

export interface UpdatePortfolioDto { [key: string]: unknown }

/**
 * Função / cargo do usuário
 */
export type RegisterDtoRole = typeof RegisterDtoRole[keyof typeof RegisterDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterDtoRole = {
  frontend: 'frontend',
  backend: 'backend',
  tester: 'tester',
  data_scientist: 'data_scientist',
  ux: 'ux',
} as const;

export interface RegisterDto {
  /**
   * Nome de usuário único
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** Email do usuário */
  email: string;
  /**
   * Senha do usuário
   * @minLength 6
   */
  password: string;
  /** Número no formato E.164 (recomendado: +55...) */
  phone: string;
  /** Função / cargo do usuário */
  role: RegisterDtoRole;
}

export interface LoginDto {
  /** Username ou email */
  usernameOrEmail: string;
  /** Senha do usuário */
  password: string;
}

export interface RequestMagicLinkDto {
  /** Email do usuário para receber o magic link */
  email: string;
}

export interface ResetPasswordDto {
  /** Token do magic link recebido por email */
  token: string;
  /**
   * Nova senha (mínimo 6 caracteres)
   * @minLength 6
   */
  newPassword: string;
}

export type CreateProjectDtoStatus = typeof CreateProjectDtoStatus[keyof typeof CreateProjectDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProjectDtoStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  TESTING: 'TESTING',
  FINISHED: 'FINISHED',
} as const;

/**
 * Habilidades técnicas (botões pré-definidos)
 */
export type CreateProjectDtoTags = typeof CreateProjectDtoTags[keyof typeof CreateProjectDtoTags];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProjectDtoTags = {
  React: 'React',
  Angular: 'Angular',
  Vue: 'Vue',
  Nodejs: 'Node.js',
  Python: 'Python',
  Java: 'Java',
  TypeScript: 'TypeScript',
  JavaScript: 'JavaScript',
  PostgreSQL: 'PostgreSQL',
  MongoDB: 'MongoDB',
  Docker: 'Docker',
  Kubernetes: 'Kubernetes',
  AWS: 'AWS',
  Azure: 'Azure',
  Git: 'Git',
} as const;

export interface CreateProjectDto {
  name: string;
  description?: string;
  status: CreateProjectDtoStatus;
  /** Habilidades técnicas (botões pré-definidos) */
  tags: CreateProjectDtoTags;
  bannerUrl: string;
  /** Número máximo de integrantes do projeto */
  membersLimit: number;
}

export interface UpdateProjectDto { [key: string]: unknown }

export interface CreateSocialDto { [key: string]: unknown }

export interface UpdateSocialDto { [key: string]: unknown }

export interface CreateIntegrationDto { [key: string]: unknown }

export interface UpdateIntegrationDto { [key: string]: unknown }

export interface CreateNotificationDto { [key: string]: unknown }

export interface UpdateNotificationDto { [key: string]: unknown }

export type AuthControllerGetResetPasswordPageParams = {
token: string;
};

