/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
export interface UpdateUserDto { [key: string]: unknown }

/**
 * Habilidades técnicas (botões pré-definidos em lowercase)
 */
export type CreatePortfolioDtoSkills = typeof CreatePortfolioDtoSkills[keyof typeof CreatePortfolioDtoSkills];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePortfolioDtoSkills = {
  react: 'react',
  angular: 'angular',
  vue: 'vue',
  nodejs: 'nodejs',
  python: 'python',
  java: 'java',
  typescript: 'typescript',
  javascript: 'javascript',
  postgresql: 'postgresql',
  mongodb: 'mongodb',
  docker: 'docker',
  kubernetes: 'kubernetes',
  aws: 'aws',
  azure: 'azure',
  git: 'git',
  css: 'css',
  html: 'html',
  mysql: 'mysql',
  express: 'express',
  jest: 'jest',
  laravel: 'laravel',
} as const;

export interface CreatePortfolioDto {
  name: string;
  bio: string;
  location: string;
  /** Número opcional no formato E.164 (pode diferir do telefone principal da conta) */
  phone?: string;
  /** Habilidades técnicas (botões pré-definidos em lowercase) */
  skills: CreatePortfolioDtoSkills[];
}

export interface UpdatePortfolioDto { [key: string]: unknown }

/**
 * Função / cargo do usuário
 */
export type RegisterDtoRole = typeof RegisterDtoRole[keyof typeof RegisterDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterDtoRole = {
  frontend: 'frontend',
  backend: 'backend',
  tester: 'tester',
  data_scientist: 'data_scientist',
  ux: 'ux',
} as const;

export interface RegisterDto {
  /**
   * Nome de usuário único
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** Email do usuário */
  email: string;
  /**
   * Senha do usuário
   * @minLength 6
   */
  password: string;
  /** Número no formato E.164 (recomendado: +55...) */
  phone: string;
  /** Função / cargo do usuário */
  role: RegisterDtoRole;
}

export interface LoginDto {
  /** Username ou email */
  usernameOrEmail: string;
  /** Senha do usuário */
  password: string;
}

export interface RequestMagicLinkDto {
  /** Email do usuário para receber o magic link */
  email: string;
}

export interface ResetPasswordDto {
  /** Token do magic link recebido por email */
  token: string;
  /**
   * Nova senha (mínimo 6 caracteres)
   * @minLength 6
   */
  newPassword: string;
}

export type CreateProjectDtoStatus = typeof CreateProjectDtoStatus[keyof typeof CreateProjectDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProjectDtoStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  TESTING: 'TESTING',
  FINISHED: 'FINISHED',
} as const;

/**
 * Habilidades técnicas (botões pré-definidos)
 */
export type CreateProjectDtoTags = typeof CreateProjectDtoTags[keyof typeof CreateProjectDtoTags];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProjectDtoTags = {
  React: 'React',
  Angular: 'Angular',
  Vue: 'Vue',
  Nodejs: 'Node.js',
  Python: 'Python',
  Java: 'Java',
  TypeScript: 'TypeScript',
  JavaScript: 'JavaScript',
  PostgreSQL: 'PostgreSQL',
  MongoDB: 'MongoDB',
  Docker: 'Docker',
  Kubernetes: 'Kubernetes',
  AWS: 'AWS',
  Azure: 'Azure',
  Git: 'Git',
} as const;

export interface CreateProjectDto {
  name: string;
  description?: string;
  status: CreateProjectDtoStatus;
  /** Habilidades técnicas (botões pré-definidos) */
  tags: CreateProjectDtoTags;
  bannerUrl: string;
  /** Número máximo de integrantes do projeto */
  membersLimit: number;
}

export interface UpdateProjectDto { [key: string]: unknown }

/**
 * Role do membro no projeto
 */
export type InviteMemberDtoRole = typeof InviteMemberDtoRole[keyof typeof InviteMemberDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InviteMemberDtoRole = {
  OWNER: 'OWNER',
  DEVELOPER: 'DEVELOPER',
  DESIGNER: 'DESIGNER',
  TESTER: 'TESTER',
  COLLABORATOR: 'COLLABORATOR',
} as const;

export interface InviteMemberDto {
  /** ID do usuário a ser convidado */
  userId: number;
  /** Role do membro no projeto */
  role?: InviteMemberDtoRole;
}

export interface RespondInvitationDto {
  /** Aceitar ou rejeitar o convite */
  accept: boolean;
}

export interface CreateSocialDto { [key: string]: unknown }

export interface UpdateSocialDto { [key: string]: unknown }

export interface CreateIntegrationDto { [key: string]: unknown }

export interface UpdateIntegrationDto { [key: string]: unknown }

export interface CreateNotificationDto { [key: string]: unknown }

export interface UpdateNotificationDto { [key: string]: unknown }

export type AuthControllerGetResetPasswordPageParams = {
token: string;
};

