/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * COOP API
 * API completa para gerenciamento de projetos colaborativos com autenticação JWT e recuperação de senha via Magic Link
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateNotificationDto,
  UpdateNotificationDto
} from '.././model';





/**
 * @summary Criar nova notificação
 */
export const notificationsControllerCreate = (
    createNotificationDto: CreateNotificationDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/notifications`,
      createNotificationDto,options
    );
  }



export const getNotificationsControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerCreate>>, TError,{data: CreateNotificationDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerCreate>>, TError,{data: CreateNotificationDto}, TContext> => {

const mutationKey = ['notificationsControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationsControllerCreate>>, {data: CreateNotificationDto}> = (props) => {
          const {data} = props ?? {};

          return  notificationsControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NotificationsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerCreate>>>
    export type NotificationsControllerCreateMutationBody = CreateNotificationDto
    export type NotificationsControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Criar nova notificação
 */
export const useNotificationsControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerCreate>>, TError,{data: CreateNotificationDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationsControllerCreate>>,
        TError,
        {data: CreateNotificationDto},
        TContext
      > => {

      const mutationOptions = getNotificationsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Listar todas as notificações
 */
export const notificationsControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/notifications`,options
    );
  }




export const getNotificationsControllerFindAllQueryKey = () => {
    return [
    `/notifications`
    ] as const;
    }

    
export const getNotificationsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsControllerFindAll>>> = ({ signal }) => notificationsControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type NotificationsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerFindAll>>>
export type NotificationsControllerFindAllQueryError = AxiosError<void>


/**
 * @summary Listar todas as notificações
 */

export function useNotificationsControllerFindAll<TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotificationsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Buscar notificação por ID
 */
export const notificationsControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/notifications/${id}`,options
    );
  }




export const getNotificationsControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/notifications/${id}`
    ] as const;
    }

    
export const getNotificationsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof notificationsControllerFindOne>>, TError = AxiosError<void | void>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsControllerFindOne>>> = ({ signal }) => notificationsControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type NotificationsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerFindOne>>>
export type NotificationsControllerFindOneQueryError = AxiosError<void | void>


/**
 * @summary Buscar notificação por ID
 */

export function useNotificationsControllerFindOne<TData = Awaited<ReturnType<typeof notificationsControllerFindOne>>, TError = AxiosError<void | void>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getNotificationsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Atualizar notificação
 */
export const notificationsControllerUpdate = (
    id: string,
    updateNotificationDto: UpdateNotificationDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.patch(
      `/notifications/${id}`,
      updateNotificationDto,options
    );
  }



export const getNotificationsControllerUpdateMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerUpdate>>, TError,{id: string;data: UpdateNotificationDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerUpdate>>, TError,{id: string;data: UpdateNotificationDto}, TContext> => {

const mutationKey = ['notificationsControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationsControllerUpdate>>, {id: string;data: UpdateNotificationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  notificationsControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NotificationsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerUpdate>>>
    export type NotificationsControllerUpdateMutationBody = UpdateNotificationDto
    export type NotificationsControllerUpdateMutationError = AxiosError<void | void>

    /**
 * @summary Atualizar notificação
 */
export const useNotificationsControllerUpdate = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerUpdate>>, TError,{id: string;data: UpdateNotificationDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationsControllerUpdate>>,
        TError,
        {id: string;data: UpdateNotificationDto},
        TContext
      > => {

      const mutationOptions = getNotificationsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Remover notificação
 */
export const notificationsControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/notifications/${id}`,options
    );
  }



export const getNotificationsControllerRemoveMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['notificationsControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  notificationsControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type NotificationsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof notificationsControllerRemove>>>
    
    export type NotificationsControllerRemoveMutationError = AxiosError<void | void>

    /**
 * @summary Remover notificação
 */
export const useNotificationsControllerRemove = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof notificationsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getNotificationsControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions);
    }
    